### ISSUE TITLE
Pills in the Discord dark theme blend into the background

### ISSUE THREAD

**Issue by anoadragon453** [aaronraimist/element-themes#10]
User/room pills are nearly invisible in the Discord Dark Theme. Is it possible to change them individually to be a bit lighter, so they stand out better?

**Comment by aaronraimist** [comment]
I had the same comment. It doesn't look like Riot gives us any variable that would allow us to set the pill color.

**Comment by thomcatdotrocks** [comment]
What we're looking for is `.mx_ReactionsRowButton.mx_ReactionsRowButton_selected` in any of the `*theme.css` files in the `/bundles/` folders.  `background-color` is the variable that needs to be changed, I manually set it to `var(--accent-color)` which looks like this:

![image](https://user-images.githubusercontent.com/37344783/75916393-dba04e00-5e1d-11ea-900d-3374f6f2daa8.png)
