### ISSUE TITLE
Docu loops around with Ansible deployment's

### ISSUE THREAD

**Issue by vitaprimo** [aaronraimist/element-themes#28]
Looking for what to do with **_matrix_client_element_themes_repository_url_** parameter it sort of guided me here, where only **_matrix_client_element_themes_enabled_** is referenced and for "more details" links to the playbook's GitHub to what it seems an [earlier resource](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-riot-web.md#themes) that links to [another resource](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-client-element.md) that only mentions what's already known, omitting matrix_client_element_themes_repository_url and pointing back to this repo's front page--which is also that's predefined in the parameter and does not work:
```
TASK [matrix-client-element : Ensure Element themes repository is pulled] **********************************************************************************************************
fatal: [matrix.domain.tld -> 127.0.0.1]: FAILED! => {"changed": false, "msg": "Failed to find required executable git in paths: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"}
```
`git` is in present where it says it's not, I even `su`ed into the corresponding user to check and it does have it. You guys should probably need to take a minute to decide who's gonna host the docu so you don't end up pointing at each other.

**Comment by aaronraimist** [comment]
The documentation is on matrix-docker-ansible-deploy as this is a feature of matrix-docker-ansible-deploy, not of element-themes: https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-client-element.md#themes

All you need to do is set `matrix_client_element_themes_enabled: true` if you want to use this repository.

You would use `matrix_client_element_themes_repository_url` if you wanted to use a *different* repository.
