### ISSUE TITLE
Am i making this wrong? (element desktop)

### ISSUE THREAD

**Issue by hrqmonteiro** [aaronraimist/element-themes#30]
I simply can't make the themes appear on my Settings in Element desktop

Here's my `config.json` file, in `.config/Element/` (I'm on Linux):

```
{
        "settingDefaults": {
        "custom_themes": [
        {
    "name": "Nord dark theme",
    "is_dark": true,
    "colors": {
        "accent-color": "#a3be8c",
        "primary-color": "#88c0d0",
        "warning-color": "#bf616a",

        "sidebar-color": "#2e3440",
        "roomlist-background-color": "#3b4252",
        "roomlist-text-color": "#ebcb8b",
        "roomlist-text-secondary-color": "#e5e9f0",
        "roomlist-highlights-color": "#2e3440",
        "roomlist-separator-color": "#434c5e",

        "timeline-background-color": "#434c5e",
        "timeline-text-color": "#eceff4",
        "timeline-text-secondary-color": "#81a1c1",
        "timeline-highlights-color": "#3b4252",
        "reaction-row-button-selected-bg-color": "#bf616a"
    }
}
        ]
    }
}
```

And the theme simply won't appear in my Appearance settings.

**Comment by aaronraimist** [comment]
I just updated the README to be a little clearer about what you need to do. In addition to what you have done so far you'll also need to add `"showLabsSettings": true` to your `config.json` and then go into the Labs section of Settings in Element to enable the custom themes feature. Once you have done that then they should show up in the Appearance settings.
