### ISSUE TITLE
Remove or update theme?

### ISSUE THREAD

**Issue by Freundsquad** [aaronraimist/element-themes#35]
I've created a personal theme to test and mess around with. However, when I change the code, I have no way to update it or remove the theme.
Is there any possible way I can do this?

**Comment by aaronraimist** [comment]
Element doesn't have a button to remove themes https://github.com/vector-im/element-web/issues/13221 or update existing themes https://github.com/vector-im/element-web/issues/13222

You would need to use `/devtools` to delete it or update it.

**Comment by MissLav** [comment]
> Element doesn't have a button to remove themes [vector-im/element-web#13221](https://github.com/vector-im/element-web/issues/13221) or update existing themes [vector-im/element-web#13222](https://github.com/vector-im/element-web/issues/13222)
> 
> You would need to use `/devtools` to delete it or update it.

sorry to reopen this but is there not just a file i could delete from the /.config/Element Dir

**Comment by dylhack** [comment]
> [vector-im/element-web#13222](https://github.com/vector-im/element-web/issues/13222)

I would ask vector-im/element-web#13222
