### ISSUE TITLE
Can a theme replace the graphical image of an emoticon?

### ISSUE THREAD

**Issue by mkarg** [aaronraimist/element-themes#46]
Can a theme replace the graphical image of an emoticon?

**Comment by mkarg** [comment]
I am asking this because I want to not just set colors. I really want to brand element. For this, I want to provide different font and emoticons.

**Comment by aaronraimist** [comment]
Themes can set the font, so yes. https://github.com/vector-im/element-web/blob/develop/docs/theming.md#custom-themes

A theme like this would use Apple's emoji rather than the default Twemoji.

```
{
  "name": "Theme with Apple Emoji",
  "is_dark": false,
  "fonts": {
    "general": "Helvetica, Apple Color Emoji, sans"
  },
...
```

**Comment by mkarg** [comment]
So this means, I must pack all my animated GIFs into a WOFF file?
