### ISSUE TITLE
Settings buttons are transparent when not active (Selenized light theme)

### ISSUE THREAD

**Issue by roughnecks** [aaronraimist/element-themes#54]
Hello,

https://i.imgur.com/dnwKFxy.gif

**Comment by aaronraimist** [comment]
Can you upload the image into this issue? You can just drag it in to the comment field and it will upload to GitHub. Imgur always gives me weird errors.

**Comment by roughnecks** [comment]
![image](https://user-images.githubusercontent.com/1666536/172352654-9fb7467f-fe08-4177-be36-dd0d703200b2.png)

Also, It's not just labs buttons, it's all of them. Thanks

**Comment by aaronraimist** [comment]
Interesting. I would suggest you open an issue on https://github.com/vector-im/element-web/issues. I doubt there is anything a theme can do here.

**Comment by roughnecks** [comment]
> Interesting. I would suggest you open an issue on https://github.com/vector-im/element-web/issues. I doubt there is anything a theme can do here.

Done, thanks: https://github.com/vector-im/element-web/issues/22492

**Comment by roughnecks** [comment]
Sorry to bother you, but is this the same stuff?

![image](https://user-images.githubusercontent.com/1666536/179419683-04efbf30-5420-4f7a-8846-308fc8d9f44b.png)

**Comment by aaronraimist** [comment]
Probably
