### ISSUE TITLE
Themes no longer applying?

### ISSUE THREAD

**Issue by K4LCIFER** [aaronraimist/element-themes#66]
It seems that these custom themes are no longer applying to element despite the configs still being set, and the Labs setting still being enabled.

- Element version: 1.11.65
- Element installed via Flatpak

**Comment by aaronraimist** [comment]
Flatpak uses a different path for the `config.json` file. Are you using the correct path? https://github.com/flathub/im.riot.Riot?tab=readme-ov-file#user-specified-configjson

**Comment by K4LCIFER** [comment]
I am using the correct path. Also I just checked with the non flatpak version, and someone from Windows also reported the same thing. The config in all cases is the same. I have tried toggling the labs setting in all cases to no avail.

**Comment by Salzi** [comment]
The problem is that `settingDefaults` is deprecated. Use `setting_defaults` instead. See also here: https://github.com/element-hq/element-web/blob/develop/docs/config.md#-deprecation-notice
